apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: trial-reserve
  description: Dot Net app. Named trial-reserve
  annotations:
    github.com/project-slug: silverkeytech/trial-reserve
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
