name: trial-reserve-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main
  workflow_dispatch:  

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{steps.set_commit_id.outputs.commit_id}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Shorten commit id
        id: set_commit_id
        run: |
          echo "commit_id=${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3      
        
      - name: Login to Gitea Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_REGISTRY }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_PAT }}

      - name: Build and push to Gitea Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.GITEA_REGISTRY }}/silverkeytech/trial-reserve:${{ steps.set_commit_id.outputs.commit_id}}


  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Install yq
        run: pip install yq


      - name: Modify values file
        run: |
          yq -i -y '
           .image.repository = "registry.arc-center.run/silverkeytech/trial-reserve" |
           .image.tag = "${{ needs.ci.outputs.commit_id }}"
           ' charts/trial-reserve/values-dev.yaml
    
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updates values.yaml with commit ${{ needs.ci.outputs.commit_id }}"

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login to ArgoCD
        run: |
          argocd login argocd.arc-center.run \
            --insecure \
            --grpc-web \
            --username admin \
            --password "${{ secrets.ARGOCD_PASSWORD }}"
            
      - name: Ensure argocd repo and app
        run: |
          repo="https://github.com/silverkeytech/trial-reserve.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          argocd app get trial-reserve || argocd app create trial-reserve \
            --repo $repo \
            --path charts/trial-reserve \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        run: |
          argocd app sync trial-reserve
          argocd app wait trial-reserve --timeout 180
